export const INITIAL_GUIDANCE_STATEMENTS = [
  "Abide silently.",
  "Be still. What notices?",
  "Be still. What sees this?",
  "Be still. What watches?",
  "Before thought. What is here?",
  "Breathe once. Who did that?",
  "Can you find the seer?",
  "Don't think. Just notice what is noticing.",
  "Drop effort.",
  "In this moment. What is present?",
  "In this moment. What notices?",
  "In this moment. What sees this?",
  "In this moment. What watches?",
  "Let go completely.",
  "Let go of trying. What remains?",
  "Let it be.",
  "Look at a sound. What sees it?",
  "Look directly. What is present?",
  "Look directly. What remains?",
  "Look directly. What sees this?",
  "Look directly. What watches?",
  "Look now. What sees thought?",
  "Look now. What is here?",
  "Look now. What notices?",
  "Look now. What sees this?",
  "Look now. What watches?",
  "Notice now. What is already present?",
  "Notice now. What is here?",
  "Notice now. What notices?",
  "Notice now. What sees this?",
  "Notice what notices.",
  "Observe gently.",
  "Pause now. What is here?",
  "Pause now. What remains?",
  "Pause now. What sees this?",
  "Pause now. What watches?",
  "Rest as awareness.",
  "Return to seeing.",
  "Right now. Are you inside, or outside?",
  "Right now. What is here?",
  "Right now. What remains?",
  "Right now. What sees this?",
  "Right now. What watches?",
  "See what sees.",
  "Stop. Look now.",
  "Stop. Where is the watcher?",
  "What hears these words?",
  "What is aware of even this seeking?",
  "What is seeing this?",
  "What sees thought?",
  "What's aware of attention?",
  "Who breathes?",
  "Who sees the mind?",
  "Who is watching?",
  "Where are you, really?"
]

export function getRandomGuidance(): string {
  const randomIndex = Math.floor(Math.random() * INITIAL_GUIDANCE_STATEMENTS.length)
  return INITIAL_GUIDANCE_STATEMENTS[randomIndex]
}